### PR TITLE
fix: return ConfigFileNotFoundError if config not found

### LINKED ISSUE #18: not getting ConfigFileNotFoundError when config file is not present
When running the app without config file, I getting `unable to read config file` error instead of `ConfigFileNotFoundError` struct.
So i am not able to catch the error in my application side.

```
if err := loader.Load(&cfg); err != nil {
		if errors.As(err, &config.ConfigFileNotFoundError{}) {
			fmt.Println(err)
		} else {
                      panic(err)
		}
	}
	
```

The error doesn't go to if condition 

Root cause of this issue is https://github.com/odpf/salt/blob/1aad792723ce5e7e0b2d55f676ba0d384b9ea09d/config/config.go#L117

due to `!ok` the error is going in else case.

### PR DESCRIPTION
**Pull request by rsbh**
fix #18

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -111,11 +111,9 @@ func (l *Loader) Load(config interface{}) error {
 
 	l.v.AutomaticEnv()
 
-	var werr error
-
 	if err := l.v.ReadInConfig(); err != nil {
-		if _, ok := err.(viper.ConfigFileNotFoundError); !ok {
-			werr = ConfigFileNotFoundError{err}
+		if _, ok := err.(viper.ConfigFileNotFoundError); ok {
```
Comment (StewartJingga) [inline config/config.go:115]: should we use `errors.As` instead?

```suggestion
		if errors.As(err, new(viper.ConfigFileNotFoundError) {
```

**Review by StewartJingga — DISMISSED** [review]
